services:
  - type: web
    name: car-price-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
